using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace reactredux.Models
{
    public class Item
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; } 

        public string Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
    }
}